# This minimal config scrape only single log file.
# Primarily used in rpm/deb packaging where promtail service can be started during system init process.
# And too much scraping during init process can overload the complete system.
# https://github.com/grafana/loki/issues/11398

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
- url: http://loki.nuc.home.arpa:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog3164
    syslog:
      listen_address: 0.0.0.0:3164
      listen_protocol: udp
      syslog_format: "rfc3164"
      label_structured_data: false
      labels:
        job: "syslog"
    pipeline_stages:
      - regex:
          expression: '^(inbound|BLOCK).+?(?P<ip>[\d.]+).*'
      - geoip:
          db: /usr/share/GeoIP/GeoLite2-City.mmdb
          source: ip
          db_type: city
      - labeldrop:
          - geoip_city_name
          - geoip_continent_code
          - geoip_continent_name
          - geoip_subdivision_code
          - geoip_subdivision_name
          - geoip_timezone
    relabel_configs:
      - source_labels: ['__syslog_connection_ip_address']
        target_label: 'ip_address'
      - source_labels: ['__syslog_message_severity']
        target_label: 'severity'
      - source_labels: ['__syslog_message_hostname']
        target_label: 'hostname'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app_name'
      - source_labels: ['__syslog_message_proc_id']
        target_label: 'proc_id'
      - source_labels: ['__syslog_message_msg_id']
        target_label: 'msg_id'
