# This minimal config scrape only single log file.
# Primarily used in rpm/deb packaging where promtail service can be started during system init process.
# And too much scraping during init process can overload the complete system.
# https://github.com/grafana/loki/issues/11398

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
- url: http://loki.nuc.home.arpa:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog3164
    syslog:
      listen_address: 0.0.0.0:3164
      listen_protocol: udp
      syslog_format: "rfc3164"
      label_structured_data: false
      labels:
        job: "syslog"
    pipeline_stages:
      - match:
          selector: '{app_name="ICP6", proc_id="075"}'
          stages:
            - drop:
                expression: '> fe80::'
      - match:
          selector: '{app_name="NAT", proc_id="061"}'
          stages:
            - regex:
                expression: '^inbound.+?(?P<ip>[\d.]+).*'
      - match:
          selector: '{app_name="FLT", proc_id="008"}'
          stages:
            - drop:
                expression: '2a04:4e42:'
            - regex:
                expression: '^BLOCK.+?\[(?P<ip>[\w:]+).*'
      - geoip:
          db: /usr/share/GeoIP/GeoLite2-City.mmdb
          source: ip
          db_type: city
      - geoip:
          db: /usr/share/GeoIP/GeoLite2-ASN.mmdb
          source: ip
          db_type: asn
      - labeldrop:
          - geoip_city_name
          - geoip_continent_code
          - geoip_continent_name
          - geoip_postal_code
          - geoip_subdivision_code
          - geoip_subdivision_name
          - geoip_timezone
    relabel_configs:
      - source_labels: ['__syslog_connection_ip_address']
        target_label: 'ip_address'
      - source_labels: ['__syslog_message_severity']
        target_label: 'severity'
      - source_labels: ['__syslog_message_hostname']
        target_label: 'hostname'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app_name'
      - source_labels: ['__syslog_message_proc_id']
        target_label: 'proc_id'
  - job_name: iap
    syslog:
      listen_address: 0.0.0.0:3165
      listen_protocol: udp
      syslog_format: "rfc3164"
      label_structured_data: false
      labels:
        job: "syslog"
    pipeline_stages:
      - drop:
          expression: 'awc_init_connection|PAPI_Send'
      - regex:
          expression: '^[\d+.]+\s(?P<app_name>\w+)\[\d+\]:\s<(?P<proc_id>\d+)>\s<\w+>\sAP:(?P<ap>[\w:]+)\s<.+?>(?P<message>.*)$'
      - drop:
          source: 'proc_id'
          expression:  '341101|326274|326276|341201|404400|404401|541004'
      - labels:
          app_name:
          proc_id:
      - match:
          selector: '{proc_id="326272"}'
          stages:
            - regex:
                expression: '= (?P<channel>\d+) SSID.*$'
      - match:
          selector: '{proc_id="404402"}'
          stages:
            - regex:
                expression: 'Type (?P<type>.*?) Signal (?P<signal>\d+) Freq (?P<freq>\d+)KHz Bandwidth (?P<bandwidth>\d+)KHz$'
      - labels:
          channel:
          type:
          signal:
          freq:
          bandwidth:
      - output:
          source: message
      - labeldrop:
        - __syslog_message_hostname
    relabel_configs:
      - source_labels: ['__syslog_connection_ip_address']
        target_label: 'ip_address'
      - source_labels: ['__syslog_message_severity']
        target_label: 'severity'
